### ISSUE TITLE
Wrong token

### ISSUE THREAD

**Issue by davidchuyaya** [cornell-dti/events-manager-ios#9]
https://github.com/cornell-dti/events-manager-ios/blob/78849f78271c7c398238719cbf96e134df699739/EventsManager/ViewControllers/LoginViewController.swift#L133

Should use `user.authentication.accessToken` instead of `user.googleIdToken`

**Comment by wsjnohyeah** [comment]
user.googleIdToken is a field in the User model. In UserData.swift, the user model is created using user.authentication.accessToken from the google sign in API.
